171044079_CSE241_HW6: Collection.o List.o Set.o Queue.o ArrayList.o HashSet.o LinkedList.o 171044079_main.o NoItemException.o
			g++ -std=c++11 Collection.o List.o ArrayList.o HashSet.o LinkedList.o 171044079_main.o NoItemException.o -o 171044079_CSE241_HW6
Collection.o: Collection.cpp
			g++ -c -std=c++11 Collection.cpp
List.o: List.cpp
			g++ -c -std=c++11 List.cpp
ArrayList.o: ArrayList.cpp
			g++ -c -std=c++11 ArrayList.cpp
HashSet.o: HashSet.cpp
			g++ -c -std=c++11 HashSet.cpp
LinkedList.o: LinkedList.cpp
			g++ -c -std=c++11 LinkedList.cpp
171044079_main.o: 171044079_main.cpp
			g++ -c -std=c++11 171044079_main.cpp
NoItemException.o: NoItemException.cpp
			g++ -c -std=c++11 NoItemException.cpp
Set.o: Set.cpp
			g++ -c -std=c++11 Set.cpp
Queue.o: Queue.cpp
			g++ -c -std=c++11 Queue.cpp
clean:
	rm *.o 171044079_CSE241_HW6

