171044079_CSE241_HW5: triangle.o rectangle.o circle.o composedShape.o polygon.o 171044079_main.o polygonVect.o polygonDyn.o globalFunc.o shape.o invalidLengthException.o invalidCoordinateException.o
		    g++ -std=c++11 composedShape.o 171044079_main.o triangle.o rectangle.o circle.o polygon.o shape.o polygonVect.o polygonDyn.o globalFunc.o invalidLengthException.o invalidCoordinateException.o -o 171044079_CSE241_HW5
triangle.o: triangle.cpp
		g++ -c -std=c++11 triangle.cpp
rectangle.o: rectangle.cpp
		g++ -c -std=c++11 rectangle.cpp
circle.o: circle.cpp
		g++ -c -std=c++11 circle.cpp
composedShape.o: composedShape.cpp 
		g++ -c -std=c++11 composedShape.cpp 
171044079_main.o: 171044079_main.cpp
		g++ -c -std=c++11 171044079_main.cpp 
polygon.o: polygon.cpp
		g++ -c -std=c++11 polygon.cpp
shape.o: shape.cpp
		g++ -c -std=c++11 shape.cpp
polygonVect.o: polygonVect.cpp
		g++ -c -std=c++11 polygonVect.cpp
polygonDyn.o: polygonDyn.cpp
		g++ -c -std=c++11 polygonDyn.cpp
globalFunc.o: globalFunc.cpp
		g++ -c -std=c++11 globalFunc.cpp
invalidLengthException.o: invalidLengthException.cpp
		g++ -c -std=c++11 invalidLengthException.cpp
invalidCoordinateException.o: invalidCoordinateException.cpp
		g++ -c -std=c++11 invalidCoordinateException.cpp
clean:
	rm *.o 171044079_CSE241_HW5
